### ISSUE TITLE
Stacktrace break format

### ISSUE THREAD

**Issue by Legion112** [dszczer/ideolog-symfony-format#10]
<img width="1426" alt="image" src="https://github.com/dszczer/ideolog-symfony-format/assets/20613430/4f51867b-c958-4b3f-b7bd-75217b36fa64">

**Comment by dszczer** [comment]
@Legion112 I've updated the pattern. Please verify if this resolved your issue.

**Comment by Legion112** [comment]
I'm no longer working on the PHP code base so I can't easily test it. 
But seems like you have mad a great job making fix 
We could close the issue.
Big thanks for keeping contributing to open source world 🙇‍♂️
