### ISSUE TITLE
New Symfony Timestamp - Adjust Regex

### ISSUE THREAD

**Issue by Surf-N-Code** [dszczer/ideolog-symfony-format#2]
It seems that Symfony has added the timezone offset to the timestamp at the beginning of each log line

`[2020-03-05T12:57:24.827849+00:00] console.DEBUG:`

Here is the adjusted regex:
`^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}\+\d{2}:\d{2}\]\s+([^.]+)\.([^:]+):\s+(.*)$`

**Comment by dszczer** [comment]
Thank you for your information. This solution will be considered as an alternative regex (regarding to log format and Symfony version, that specific user has).
